//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dodeljeni_profesori
    {
        public int ID_odeljenje { get; set; }
        public int ID_profesor { get; set; }
        [Key]
        public int ID_dp { get; set; }
    
        public virtual Odeljenja Odeljenja { get; set; }
        public virtual Profesori Profesori { get; set; }
    }
}
