//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eDnevnik_v4Entities2 : DbContext
    {
        public eDnevnik_v4Entities2()
            : base("name=eDnevnik_v4Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dodeljene_ocene> Dodeljene_ocene { get; set; }
        public virtual DbSet<Dodeljeni_profesori> Dodeljeni_profesori { get; set; }
        public virtual DbSet<Ocene> Ocene { get; set; }
        public virtual DbSet<Odeljenja> Odeljenja { get; set; }
        public virtual DbSet<Predmeti> Predmeti { get; set; }
        public virtual DbSet<Predmetni_profesori> Predmetni_profesori { get; set; }
        public virtual DbSet<Profesori> Profesori { get; set; }
        public virtual DbSet<Tipovi_ocena> Tipovi_ocena { get; set; }
        public virtual DbSet<Ucenici> Ucenici { get; set; }
    }
}
