//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeljenja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odeljenja()
        {
            this.Dodeljeni_profesori = new HashSet<Dodeljeni_profesori>();
            this.Ucenicis = new HashSet<Ucenici>();
        }
    
        public int ID_odeljenje { get; set; }
        public int broj_odeljenja { get; set; }
        public int godina_skolovanja { get; set; }
        public int staresina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dodeljeni_profesori> Dodeljeni_profesori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucenici> Ucenicis { get; set; }
        public virtual Profesori Profesori { get; set; }
    }
}
