//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmetni_profesori
    {
        public int ID_profesor { get; set; }
        public int ID_predmet { get; set; }
        public Nullable<System.DateTime> datum_dodele { get; set; }
    
        public virtual Predmeti Predmeti { get; set; }
        public virtual Profesori Profesori { get; set; }
    }
}
